'use client';

import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'ta';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

const translations = {
  en: {
    home: 'Home',
    collections: 'Collections',
    contact: 'Contact Us',
    billing: 'Billing',
    heroTitle: 'Sri Balamurugan Tanker Welding Labour Works',
    heroSubtitle: 'Premium Quality Tanker Welding & Fabrication Services',
    petrolTanks: 'Petrol Tanks',
    waterTanks: 'Water Tanks',
    chemicalTanks: 'Chemical Tanks',
    milkTanks: 'Milk Tanks',
    oilTanks: 'Edible Oil Tanks',
    bitumenTanks: 'Bitumen Tanks',
    acidTanks: 'Acid Tanks',
    foodGradeTanks: 'Food Grade Tanks',
    bookOrder: 'Book an Order',
    bookCall: 'Book a Call',
    adminAccess: 'Admin Access',
    invoiceNumber: 'Invoice #',
    clientName: 'Client Name',
    amount: 'Amount',
    date: 'Date',
    actions: 'Actions',
    createBill: 'Create New Bill',
    saveBill: 'Save Bill',
    delete: 'Delete',
    name: 'Name',
    mobileNumber: 'Mobile Number',
    description: 'Description',
    submit: 'Submit',
    close: 'Close',
    bookCallSuccess: 'Call booked successfully!',
    tankerType: 'Tanker Type',
    vehicleType: 'Vehicle Type',
    vehicleNumber: 'Vehicle Number Plate',
    bookOrderSuccess: 'Order booked successfully!',
    selectTanker: '-- Select Tanker Type --',
    selectVehicle: '-- Select Vehicle Type --',
    lorry: 'Lorry',
    trailer: 'Trailer',
    tractor: 'Tractor',
    addressLabel: 'Address',
    addressText: 'Salem - Namakkal Highway, Namakkal, Tamil Nadu 637001',
    gallery: 'Gallery',
    viewAllImages: 'View All Images',
    showLess: 'Show Less',
    slideshowTitle: 'Project Showcase',
    slideshowSubtitle: 'Explore our premium quality welding and fabrication works',
    nextImage: 'Next Image',
    prevImage: 'Previous Image',
    closeGallery: 'Close Gallery',
    
    // Billing System Additions
    overview: 'Overview',
    billingWizard: 'Billing Wizard',
    configurations: 'Configurations',
    performanceAudit: 'Performance & Audit',
    referenceGallery: 'Reference Gallery',
    settings: 'Settings',
    signOut: 'Sign Out',
    online: 'Online',
    enterPin: 'Enter Admin PIN',
    setPinTitle: 'Set Admin PIN',
    pinSubtitle: 'Enter your 6-digit PIN to access billing.',
    pinSubtitleSet: 'Create a 6-digit PIN for future access.',
    showPin: 'Show PIN',
    unlock: 'Unlock',
    setPinBtn: 'Set PIN',
    forgotPin: 'Forgot PIN? Reset All Billing Data',
    labourBill: 'Labour Bill',
    startWizard: 'Start Invoice →',
    manageInventory: 'Manage Products & Vehicles',
    openSettings: 'Open Settings →',
    performanceAnalysis: 'Performance & Analysis',
    openDashboard: 'Open Dashboard →',
    invoiceHistory: 'Invoice Register History',
    invoiceNo: 'Invoice No',
    type: 'Type',
    clientCompany: 'Client/Company',
    grandTotal: 'Grand Total',
    actionsLabel: 'Actions',
    labourLabel: 'Labour',
    draftLabel: 'Draft',
    vehicleLabel: 'Vehicle',
    viewLabel: 'View',
    editDraftLabel: 'Edit Draft',
    deleteLabel: 'Delete',
    noBillsText: 'No bills found in this register. Select a model above to generate one.',
    labourStep1Title: 'Labour Bill: Setup Details',
    vehiclePlateLabel: 'Vehicle Plate Number (e.g. TN 01 AA 1234)',
    companyClientLabel: 'Company / Client Name',
    selectCompany: '-- Select Company --',
    customCompanyLabel: 'Specify Custom Company Name',
    cancel: 'Cancel',
    nextSelectWorks: 'Next: Select Works →',
    selectBillModeTitle: 'Select Billing Mode',
    instantBillLabel: 'Instant Bill',
    draftBillLabel: 'Draft Bill',
    selectWorksTitle: 'Select Works Performed',
    checkServicesLabel: 'Check the services that apply:',
    searchPlaceholder: '🔍 Search service/product (e.g. welding, dome, valve...)',
    noWorksText: 'No matching works found. Use the custom work input below to add it directly!',
    addCustomWork: 'Add other custom work...',
    addWorkBtn: '+ Add Work',
    nextBuildLedger: 'Next: Build Ledger →',
    ledgerSetupTitle: 'Labour Bill Ledger Setup',
    sNo: 'S.No',
    serviceDescription: 'Service Description',
    qty: 'Qty',
    rateRupees: 'Rate (₹)',
    amountRupees: 'Amount (₹)',
    describeWeldingPlaceholder: 'Describe the welding/fabrication work done...',
    addWorkBtnLedger: '🛠️ Add Work',
    saveAsDraft: '💾 Save as Draft',
    finalizeSaveInvoice: '✔ Finalize & Save Invoice',
    generateSaveInvoice: '✔ Generate & Save Labour Invoice',
    manageProductsTitle: 'Manage Products & Companies',
    manageProductsSub: 'Configure default services (products) and preset transport companies available in the system.',
    weldingWorksTitle: '🛠️ Welding Works / Services (Products)',
    addProduct: '+ Add Product',
    addCompany: '+ Add Company',
    noServicesText: 'No services defined. Add one above!',
    presetCompaniesTitle: 'Preset Transport Companies',
    referenceGalleryTitle: '📸 Product & Vehicle Reference Images Gallery',
    addWorkImage: '📤 Add Work Image',
    noImagesText: 'No reference images added yet. Click "Add Work Image" above to upload photos!',
    closeSettings: 'Close Settings',
    performanceTitle: 'Sri Balamurugan Performance Analytics',
    performanceSub: 'System wide performance audit and billing registers.',
    dateAuditorTitle: 'Date Range Auditor',
    fromDate: 'From Date:',
    toDate: 'To Date:',
    billsSubmitted: 'Bills Submitted',
    totalRevenue: 'Total Revenue',
    auditRegisterTitle: 'Audit Register For This Range:',
    noLogsText: 'No register logs found for this date range.',
    fourMonthPerformance: '4-Month Business Performance',
    revenueTrend: 'Revenue Trend',
    billVolumeTrend: 'Bill Volume Trend',
    closeDashboard: 'Close Dashboard',
    printPdf: '🖨️ Print / Save as PDF',
    closeRegister: 'Close Register',
    corporateTitle: 'SRI BALAMURUGAN TANKER WELDING',
    corporateSub: 'Specialists in Heavy Tankers, Gas Linings, Dairy & Oil Fleet Repair Works',
    corporateDetails: 'Salem - Namakkal Highway, Namakkal, Tamil Nadu 637001',
    invoiceRegisterTitle: 'INVOICE REGISTER',
    billedTo: 'BILLED TO:',
    invoiceDetails: 'INVOICE DETAILS:',
    statusLabel: 'Status:',
    statusPaid: 'PAID',
    authorizedSignature: 'Authorized Signature',
    footerTerms: 'Thank you for your business. Terms of Service: All repairs are certified for high-pressure operations. In case of leaks, notify immediately within 30 days.',
    enterOtpTitle: 'Enter OTP Code',
    otpSubtitle: 'A 6-digit OTP verification code has been simulated and sent to your registered mobile number.',
    resendOtp: 'Resend OTP',
    backToPin: 'Back to PIN',
    verifyAccess: 'Verify & Access Registers',
    smsNotification: 'SMS Notification Simulator',
    smsNotificationBody: 'Your Sri Balamurugan Admin verification OTP is: ',
    otpError: 'Incorrect OTP. Please check the simulated SMS alert and try again.',
    errorLabel: 'An error occurred. Please try again.',
  },
  ta: {
    home: 'முகப்பு',
    collections: 'தொகுப்புகள்',
    contact: 'தொடர்பு கொள்ள',
    billing: 'பட்டியலிடல்',
    heroTitle: 'ஸ்ரீ பாலமுருகன் டேங்கர் வெல்டிங் லேபர் ஒர்க்ஸ்',
    heroSubtitle: 'உயர்தர டேங்கர் வெல்டிங் மற்றும் உற்பத்தி சேவைகள்',
    petrolTanks: 'பெட்ரோல் டாங்கிகள்',
    waterTanks: 'தண்ணீர் டாங்கிகள்',
    chemicalTanks: 'ரசாயன டாங்கிகள்',
    milkTanks: 'பால் டாங்கிகள்',
    oilTanks: 'சமையல் எண்ணெய் டாங்கிகள்',
    bitumenTanks: 'பிற்றுமின் டாங்கிகள்',
    acidTanks: 'அமில டாங்கிகள்',
    foodGradeTanks: 'உணவு தர டாங்கிகள்',
    bookOrder: 'ஆர்டர் செய்ய',
    bookCall: 'அழைப்பை முன்பதிவு செய்ய',
    adminAccess: 'நிர்வாகி அணுகல்',
    invoiceNumber: 'பட்டியல் #',
    clientName: 'வாடிக்கையாளர் பெயர்',
    amount: 'தொகை',
    date: 'தேதி',
    actions: 'செயல்கள்',
    createBill: 'புதிய பட்டியல் உருவாக்கு',
    saveBill: 'பட்டியலை சேமி',
    delete: 'நீக்கு',
    name: 'பெயர்',
    mobileNumber: 'கைபேசி எண்',
    description: 'விளக்கம்',
    submit: 'சமர்ப்பி',
    close: 'மூடு',
    bookCallSuccess: 'அழைப்பு வெற்றிகரமாக முன்பதிவு செய்யப்பட்டது!',
    tankerType: 'டாங்கர் வகை',
    vehicleType: 'வாகன வகை',
    vehicleNumber: 'வாகனத்தின் பதிவு எண்',
    bookOrderSuccess: 'ஆர்டர் வெற்றிகரமாக முன்பதிவு செய்யப்பட்டது!',
    selectTanker: '-- டாங்கர் வகையைத் தேர்ந்தெடுக்கவும் --',
    selectVehicle: '-- வாகன வகையைத் தேர்ந்தெடுக்கவும் --',
    lorry: 'லாரி',
    trailer: 'டிரெய்லர்',
    tractor: 'டிராக்டர்',
    addressLabel: 'முகவரி',
    addressText: 'சேலம் - நாமக்கல் நெடுஞ்சாலை, நாமக்கல், தமிழ்நாடு 637001',
    gallery: 'புகைப்பட தொகுப்பு',
    viewAllImages: 'அனைத்து புகைப்படங்களையும் காண்க',
    showLess: 'குறைவாகக் காட்டு',
    slideshowTitle: 'திட்டங்களின் கண்காட்சி',
    slideshowSubtitle: 'எங்களின் உயர்தர வெல்டிங் மற்றும் உற்பத்தி வேலைகளை ஆராயுங்கள்',
    nextImage: 'அடுத்த படம்',
    prevImage: 'முந்தைய படம்',
    closeGallery: 'மூடு',

    // Billing System Additions (Tamil)
    overview: 'கண்ணோட்டம்',
    billingWizard: 'பட்டியலிடல் வழிகாட்டி',
    configurations: 'கட்டமைப்புகள்',
    performanceAudit: 'செயல்திறன் தணிக்கை',
    referenceGallery: 'புகைப்பட தொகுப்பு',
    settings: 'அமைப்புகள்',
    signOut: 'வெளியேறு',
    online: 'ஆன்லைன்',
    enterPin: 'நிர்வாகி PIN ஐ உள்ளிடவும்',
    setPinTitle: 'நிர்வாகி PIN ஐ அமைக்கவும்',
    pinSubtitle: 'பட்டியலிடலை அணுக உங்கள் 6-இலக்க PIN ஐ உள்ளிடவும்.',
    pinSubtitleSet: 'எதிர்கால அணுகலுக்கு 6-இலக்க PIN ஐ உருவாக்கவும்.',
    showPin: 'PIN ஐக் காண்பி',
    unlock: 'அன்லாக் செய்',
    setPinBtn: 'PIN ஐ அமை',
    forgotPin: 'PIN மறந்துவிட்டதா? அனைத்து தரவையும் மீட்டமைக்கவும்',
    labourBill: 'லேபர் பட்டியல்',
    startWizard: 'இன்வாய்ஸைத் தொடங்கு →',
    manageInventory: 'தயாரிப்புகள் & வாகனங்கள் நிர்வகி',
    openSettings: 'அமைப்புகளைத் திற →',
    performanceAnalysis: 'செயல்திறன் & பகுப்பாய்வு',
    openDashboard: 'டாஷ்போர்டைத் திற →',
    invoiceHistory: 'பட்டியல் பதிவு வரலாறு',
    invoiceNo: 'பட்டியல் எண்',
    type: 'வகை',
    clientCompany: 'வாடிக்கையாளர்/நிறுவனம்',
    grandTotal: 'மொத்த தொகை',
    actionsLabel: 'செயல்கள்',
    labourLabel: 'லேபர்',
    draftLabel: 'வரைவு',
    vehicleLabel: 'வாகனம்',
    viewLabel: 'காண்க',
    editDraftLabel: 'வரைவை திருத்து',
    deleteLabel: 'நீக்கு',
    noBillsText: 'பதிவேட்டில் பட்டியல்கள் எதுவும் இல்லை. ஒன்றை உருவாக்க மேலே உள்ள மாதிரியைத் தேர்ந்தெடுக்கவும்.',
    labourStep1Title: 'லேபர் பட்டியல்: வடிவமைப்பு விவரங்கள்',
    vehiclePlateLabel: 'வாகன பதிவு எண் (உதாரணம்: TN 01 AA 1234)',
    companyClientLabel: 'நிறுவனம் / வாடிக்கையாளர் பெயர்',
    selectCompany: '-- நிறுவனத்தைத் தேர்ந்தெடுக்கவும் --',
    customCompanyLabel: 'விருப்ப நிறுவனத்தின் பெயரைக் குறிப்பிடவும்',
    cancel: 'ரத்துசெய்',
    nextSelectWorks: 'அடுத்து: வேலைகளைத் தேர்ந்தெடுக்கவும் →',
    selectBillModeTitle: 'பட்டியல் பயன்முறையைத் தேர்ந்தெடுக்கவும்',
    instantBillLabel: 'உடனடி பட்டியல்',
    draftBillLabel: 'வரைவு பட்டியல்',
    selectWorksTitle: 'செய்த வேலைகளைத் தேர்ந்தெடுக்கவும்',
    checkServicesLabel: 'பொருந்தும் சேவைகளைத் தேர்ந்தெடுக்கவும்:',
    searchPlaceholder: '🔍 சேவையைத் தேடுங்கள் (உதாரணம்: வெல்டிங், டோம், வால்வு...)',
    noWorksText: 'பொருந்தும் வேலைகள் எதுவும் இல்லை. நேரடியாகச் சேர்க்க கீழே உள்ள விருப்ப உள்ளீட்டைப் பயன்படுத்தவும்!',
    addCustomWork: 'மற்ற வேலைகளைச் சேர்க்கவும்...',
    addWorkBtn: '+ வேலை சேர்',
    nextBuildLedger: 'அடுத்து: லெட்ஜர் உருவாக்கு →',
    ledgerSetupTitle: 'லேபர் பட்டியல் லெட்ஜர் வடிவமைப்பு',
    sNo: 'வ.எண்',
    serviceDescription: 'சேவை விவரம்',
    qty: 'அளவு',
    rateRupees: 'விகிதம் (₹)',
    amountRupees: 'தொகை (₹)',
    describeWeldingPlaceholder: 'செய்யப்பட்ட வெல்டிங்/தயாரிப்பு வேலையை விவரிக்கவும்...',
    addWorkBtnLedger: '🛠️ வேலை சேர்',
    saveAsDraft: '💾 வரைவாகச் சேமி',
    finalizeSaveInvoice: '✔ இன்வாய்ஸை சேமிக்கவும்',
    generateSaveInvoice: '✔ லேபர் இன்வாய்ஸை உருவாக்கி சேமிக்கவும்',
    manageProductsTitle: 'தயாரிப்புகள் & நிறுவனங்களை நிர்வகி',
    manageProductsSub: 'கணினியில் கிடைக்கும் இயல்புநிலை சேவைகளையும் நிறுவனங்களையும் கட்டமைக்கவும்.',
    weldingWorksTitle: '🛠️ வெல்டிங் வேலைகள் / சேவைகள்',
    addProduct: '+ தயாரிப்பைச் சேர்',
    addCompany: '+ நிறுவனத்தைச் சேர்',
    noServicesText: 'சேவைகள் எதுவும் வரையறுக்கப்படவில்லை. மேலே சேர்க்கவும்!',
    presetCompaniesTitle: 'நிறுவனங்களின் பட்டியல்',
    referenceGalleryTitle: '📸 தயாரிப்பு & வாகன குறிப்பு புகைப்படங்கள்',
    addWorkImage: '📤 புகைப்படத்தை சேர்',
    noImagesText: 'குறிப்பு படங்கள் எதுவும் இன்னும் சேர்க்கப்படவில்லை. பதிவேற்ற மேலே உள்ள "புகைப்படத்தை சேர்" என்பதை அழுத்தவும்!',
    closeSettings: 'அமைப்புகளை மூடு',
    performanceTitle: 'ஸ்ரீ பாலமுருகன் செயல்திறன் பகுப்பாய்வு',
    performanceSub: 'கணினி அளவிலான செயல்திறன் தணிக்கை மற்றும் பட்டியல் பதிவேடுகள்.',
    dateAuditorTitle: 'தேதி வரம்பு தணிக்கையாளர்',
    fromDate: 'தொடக்க தேதி:',
    toDate: 'முடிவு தேதி:',
    billsSubmitted: 'சமர்ப்பிக்கப்பட்ட பட்டியல்கள்',
    totalRevenue: 'மொத்த வருவாய்',
    auditRegisterTitle: 'இந்த வரம்பிற்கான தணிக்கை பதிவேடு:',
    noLogsText: 'இந்த தேதி வரம்பில் பதிவுகள் எதுவும் இல்லை.',
    fourMonthPerformance: '4-மாத வணிக செயல்திறன்',
    revenueTrend: 'வருவாய் போக்கு',
    billVolumeTrend: 'பட்டியல் அளவின் போக்கு',
    closeDashboard: 'டாஷ்போர்டை மூடு',
    printPdf: '🖨️ அச்சிடு / PDF ஆக சேமி',
    closeRegister: 'பதிவேட்டை மூடு',
    corporateTitle: 'ஸ்ரீ பாலமுருகன் டேங்கர் வெல்டிங்',
    corporateSub: 'கனரக டேங்கர்கள், கேஸ் லைனிங்ஸ், பால் & எண்ணெய் வாகன பழுதுபார்க்கும் பணிகளில் நிபுணர்கள்',
    corporateDetails: 'சேலம் - நாமக்கல் நெடுஞ்சாலை, நாமக்கல், தமிழ்நாடு 637001',
    invoiceRegisterTitle: 'இன்வாய்ஸ் பதிவேடு',
    billedTo: 'யாருக்கு அனுப்பப்பட்டது:',
    invoiceDetails: 'இன்வாய்ஸ் விவரங்கள்:',
    statusLabel: 'நிலை:',
    statusPaid: 'PAID',
    authorizedSignature: 'அங்கீகரிக்கப்பட்ட கையொப்பம்',
    footerTerms: 'உங்கள் வணிகத்திற்கு நன்றி. சேவை விதிமுறைகள்: அனைத்து பழுதுபார்ப்புகளும் சான்றளிக்கப்பட்டவை. கசிவு ஏற்பட்டால், 30 நாட்களுக்குள் தெரிவிக்கவும்.',
    enterOtpTitle: 'OTP குறியீட்டை உள்ளிடவும்',
    otpSubtitle: '6-இலக்க OTP சரிபார்ப்புக் குறியீடு உருவகப்படுத்தப்பட்டு உங்கள் பதிவு செய்யப்பட்ட கைபேசி எண்ணிற்கு அனுப்பப்பட்டுள்ளது.',
    resendOtp: 'OTP ஐ மீண்டும் அனுப்பு',
    backToPin: 'மீண்டும் PIN திரைக்கு',
    verifyAccess: 'சரிபார்த்து பதிவேடுகளை அணுகவும்',
    smsNotification: 'SMS அறிவிப்பு உருவகப்படுத்துதல்',
    smsNotificationBody: 'உங்கள் ஸ்ரீ பாலமுருகன் நிர்வாகி சரிபார்ப்பு OTP: ',
    otpError: 'தவறான OTP. சரிபார்ப்புக் குறியீட்டைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    errorLabel: 'பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: keyof typeof translations.en) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
